version: '2'

services:
  ipfs:
    image: airalab/ipfs-cloud 
    restart: always
    expose:
    - 5001
    volumes:
    - ipfsdata:/ipfs 

  parity:
    image: airalab/parity-cloud:unstable
    restart: always
    expose:
    - 8545
    environment:
    - CHAIN=kovan

  robot:
    build: .
    restart: always
    depends_on:
    - ipfs
    - parity
    volumes:
    - ./state:/home/ros/state
    environment:
    - IPFS_NODE=ipfs
    - PARITY_NODE=parity
    - PERIOD=60
    - LIABILITY_CONTRACT=0x5fe40B387a03bDa5649d70Fb5be1D7A55Fb5BA42

volumes:
  ipfsdata:
