version: '2'

services:
  ipfs:
    image: airalab/ipfs-cloud 
    restart: always
    expose:
    - 5001
    volumes:
    - ipfsdata:/ipfs 

  parity:
    image: airalab/parity-cloud:unstable
    restart: always
    expose:
    - 8545
    environment:
    - CHAIN=kovan

  robot:
    build: .
    restart: always
    depends_on:
    - ipfs
    - parity
    volumes:
    - ./state:/home/ros/state
    environment:
    - IPFS_NODE=ipfs
    - PARITY_NODE=parity
    - PERIOD=60
    - MARKET_CONTRACT=0x65b2BB7468E27060070008ce80242e8419eF7b1D

volumes:
  ipfsdata:
