version: '2'

services:
  ipfs:
    image: airalab/ipfs-cloud 
    restart: always
    expose:
    - 5001
    volumes:
    - ipfsdata:/ipfs 

  parity:
    image: airalab/parity-cloud:unstable
    restart: always
    expose:
    - 8545
    volumes:
    - chaindata:/root/.local/share/io.parity.ethereum
    environment:
    - CHAIN=kovan

  robot:
    build: .
    restart: always
    depends_on:
    - ipfs
    - parity
    volumes:
    - ./state:/home/ros/state
    - confdata:/conf
    environment:
    - IPFS_NODE=ipfs
    - PARITY_NODE=parity
    - NODE_PATH=/usr/local/lib/node_modules

  agent:
    build: ../agent
    restart: always
    depends_on:
    - ipfs
    - parity
    ports:
    - "8000:80"
    volumes:
    - chaindata:/chain
    - confdata:/conf
    environment:
    - IPFS_NODE=ipfs
    - DAPP_IPNS=QmSkzXiapTToWfSxgh9dUXtjMmFaWFuJog6TyueeWyLZJS

  market:
    build: ../market
    restart: always
    depends_on:
    - parity
    volumes:
    - confdata:/conf
    environment:
    - PARITY_NODE=parity
    - NODE_PATH=/usr/local/lib/node_modules

volumes:
  ipfsdata:
  chaindata:
  confdata:
