version: '2'

services:
  ipfs:
    image: airalab/ipfs-cloud 
    restart: always
    expose:
    - 5001
    - 80
    volumes:
    - ipfsdata:/ipfs 

  parity:
    image: airalab/parity-cloud:unstable
    restart: always
    expose:
    - 8545
    volumes:
    - chaindata:/root/.local/share/io.parity.ethereum
    environment:
    - CHAIN=kovan

  agent:
    build: .
    restart: always
    depends_on:
    - ipfs
    - parity
    ports:
    - "8000:80"
    volumes:
    - chaindata:/chain
    - confdata:/conf
    environment:
    - IPFS_NODE=ipfs
    - DAPP_IPNS=QmQCt9UBAsSHa6BVCK6HYzJjrab63xiT2i6uoa751BVcJ4

volumes:
  ipfsdata:
  chaindata:
  confdata:
